name: Deploy Function

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      PROJECT_ID: iazmjdjwnkilycbjwpzp
      FUNCTION_SECRET: ${{ secrets.FUNCTION_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - uses: supabase/setup-cli@v1
        with:
          version: 1.0.0

      - run: supabase functions deploy hello --project-ref $PROJECT_ID --no-verify-jwt
      - run: supabase functions deploy og-image --project-ref $PROJECT_ID --no-verify-jwt
      - run: supabase functions deploy telegram-bot --project-ref $PROJECT_ID --no-verify-jwt
      - run: supabase functions deploy ai-response --project-ref $PROJECT_ID --no-verify-jwt
      # - run: supabase functions deploy image-resizer --project-ref $PROJECT_ID --no-verify-jwt
